services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql_db
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: : ROOT_PASSWORD
      MYSQL_DATABASE: DATABASE_NAME
      MYSQL_USER: DATABASE_USER_NAME
      MYSQL_PASSWORD: DATABASE_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local