services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql_db
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: quick_mart_db
      MYSQL_USER: quick_mart_db_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
  quickmart:
    build:
      context: .
      dockerfile: Dockerfile-slim
    container_name: quickmart
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - quick_mart_data:/app/quick_mart/logs
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/quick_mart_db
      - DATABASE_USERNAME=quick_mart_db_user
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  filebeat:
    build:
      context: .
      dockerfile: Dockerfile-filebeat
    container_name: filebeat
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - quick_mart_data:/app/quick_mart/logs
    depends_on:
      - quickmart
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  quick_mart_data:
  esdata:
  mysql_data: