FROM maven:3.9.7-sapmachine-21 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:21-ea-30-slim-bullseye

WORKDIR /app

COPY --from=build /app/target/quick-mart-0.0.1-SNAPSHOT.jar /app/quick-mart.jar

EXPOSE 8080

CMD ["java", "-jar", "quick-mart.jar"]
