services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql_db
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 30e0166717fb1790be50c908438a5509
      MYSQL_DATABASE: quick_mart_db
      MYSQL_USER: quick_mart_db_user
      MYSQL_PASSWORD: a1643af38034caaa687ae9e12f68dc6d
    volumes:
      - mysql_data:/var/lib/mysql
  quickmart:
    build:
      context: .
      dockerfile: Dockerfile-slim
    container_name: quickmart
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/quick_mart_db
      - DATABASE_USERNAME=quick_mart_db_user
      - DATABASE_PASSWORD=a1643af38034caaa687ae9e12f68dc6d
  filebeat:
    build:
      context: .
      dockerfile: Dockerfile-filebeat
    container_name: filebeat
    volumes:
      - logs:/app/logs
    depends_on:
      - quickmart
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=62be9d2b8db86e359af6115ae5184e3d
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  logs:
    driver: local
  esdata:
    driver: local
  mysql_data:
    driver: local