filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/*.log

output.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]
  username: "elastic"
  password: "62be9d2b8db86e359af6115ae5184e3d"
