filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/*.log

output.elasticsearch:
  hosts: [ "${ELASTICSEARCH_HOSTS}" ]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
